# https://github.com/probot/semantic-pull-requests#configuration

# Always validate the PR title AND all the commits
titleAndCommits: true

# Allow use of Merge commits (eg on github: "Merge branch 'main' into
# feature/ride-unicorns") this is only relevant when using commitsOnly: true
# (or titleAndCommits: true)
allowMergeCommits: true
