# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use fixed version to not introduce new linters unexpectedly

linters:
  enable-all: true
  disable:
    # code to be refactored at some point
    # but seems necessary to have global variables
    - gochecknoglobals

linters-settings:
  lll:
    line-length: 142

run:
  tests: false
