---
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - err113
    - errorlint
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - misspell
    # - mnd
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck

linters-settings:
  lll:
    line-length: 142
  funlen:
    lines: 120
    statements: 80
  gocognit:
    min-complexity: 60
  gosec:
    excludes:
      - G115

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - err113
        - errcheck
        - funlen
        - gocritic
        - gosec
        - lll
        - nestif
        - paralleltest
        - staticcheck
        - testpackage
run:
  timeout: 5m
