---
name: 'Check Title and Commits'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: check_pr_title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          scopes: |
            core
            drivers
            pkg
            deps
            error
            release
            util
